[package]
name = "spacetimedb-client-api-messages"
version = "0.8.1"
edition = "2021"
license-file = "LICENSE"
description = "Types for the SpacetimeDB client API messages"

[dependencies]
prost.workspace = true
strum.workspace = true

[build-dependencies]
prost-build.workspace = true
